function [labels] = time_domain_labels()
    labels = {'Mean'...
                  'RMS',...
    'StandardDeviation',...
          'ShapeFactor',...
                  'SNR',...
                  'THD',...
                'SINAD',...
            'PeakValue',...
          'CrestFactor',...
      'ClearanceFactor',...
        'ImpulseFactor',...
        'skewness',...
        'kurtosis'};
end

