function [labels] = time_domain_labels()
%Returns the frequency domain features computed by frecuency_domain_stats()
    labels = {'Mean'...
                  'RMS',...
    'StandardDeviation',...
          'ShapeFactor',...
          'SINAD', ...
          'SHR',...
          'THD',...
            'PeakValue',...
          'CrestFactor',...
      'ClearanceFactor',...
        'ImpulseFactor',...
        'skewness',...
        'kurtosis'};
end

